### ISSUE TITLE
example code does not work

### ISSUE THREAD

**Issue by dbrami** [cokelaer/reports#4]
Hi Thomas,
I'm getting an error trying to get the example code to run (attaching file).

Here's the error:
```Traceback (most recent call last):
  File "./reportsTest.py", line 19, in <module>
    table.add_bgcolor('Frequency', cmap="copper")
  File "/Users/dbrami/Flask/lib/python2.7/site-packages/reports/htmltable.py", line 161, in add_bgcolor
    rgbcolors = [cmap(x)[0:3] for x in data]
TypeError: 'str' object is not callable

Process finished with exit code 1
```
[reportsTest.py.zip](https://github.com/cokelaer/reports/files/863246/reportsTest.py.zip)

**Comment by cokelaer** [comment]
surely a python 2/3 issue. closing. won't be fix
